"""The Complete Residual Register — All Known to Man.

Transcribed from the source document. Each entry is
    (class_id, residual_id, name, source, arity)
Classes are given in CLASSES below.
"""
from __future__ import annotations

from dataclasses import dataclass

CLASSES: dict[str, str] = {
    "I":   "Thread",
    "II":  "Mathematical",
    "III": "Logical",
    "IV":  "Computational",
    "V":   "Physical",
    "VI":  "Information-Theoretic",
    "VII": "Cryptographic",
    "VIII":"Type-Theoretic",
    "IX":  "Categorical",
    "X":   "Architectural",
    "XI":  "Epistemic",
    "XII": "Statistical",
    "XIII":"Governance",
    "XIV": "Economic",
    "XV":  "Distributed Systems",
    "XVI": "Physical Implementation",
    "XVII":"Cognitive",
    "XVIII":"Semantic",
    "XIX": "Ethical",
    "XX":  "Legal",
    "XXI": "Biological",
    "XXII":"Systems",
    "XXIII":"Foundational",
    "XXIV":"Terminal",
}

# (class_id, residual_id, name, source, arity)
ENTRIES: list[tuple] = [
    # ── Part I — Thread ──────────────────────────────────────
    ("I","T-01","Intent Chain (R01 has no input)","Genesis regress",0),
    ("I","T-02","Chooser Intent set (R02)","Selection is external",1),
    ("I","T-03","Frame commitment","Frame closure is stipulated",1),
    ("I","T-04","Spec drafting","Informal→formal gap",1),
    ("I","T-05","Translation faithfulness","Semantics preservation",1),
    ("I","T-06","WF acceptance","Wellformedness ≠ correctness",1),
    ("I","T-07","Invariant selection","Design choice",1),
    ("I","T-08","Decomposition minimality","NP-hard in general",1),
    ("I","T-09","Composition law","Composition ≠ sum","N"),
    ("I","T-10","Compiler correctness","Compiler bug",1),
    ("I","T-11","Generator determinism","Nondeterministic templates",1),
    ("I","T-12","Optimality","Undecidable",1),
    ("I","T-13","Solver completeness","unknown result",1),
    ("I","T-14","Search space size","Exponential",1),
    ("I","T-15","Pruning soundness","May discard valid candidates",1),
    ("I","T-16","Prover termination","Timeout",2),
    ("I","T-17","Kernel soundness","Kernel bug",1),
    ("I","T-18","Refuter completeness","Absence of counterexample ≠ proof",2),
    ("I","T-19","Environment reproducibility","Env drift",2),
    ("I","T-20","Symbol resolution","Collision","N"),
    ("I","T-21","Bit-identical reproduction","Timestamps, entropy",1),
    ("I","T-22","Loader integrity","Loader correctness",1),
    ("I","T-23","Trace honesty","Observer dependency",2),
    ("I","T-24","Scheduling policy","Policy stipulated",1),
    ("I","T-25","Observability rank","Structural blind spots",1),
    ("I","T-26","Measurement disturbance","Landauer",1),
    ("I","T-27","Between-sample gap","Finite sampling",1),
    ("I","T-28","Nonce freshness","Clock trust",1),
    ("I","T-29","Ledger independence","Notary control",1),
    ("I","T-30","PQC migration window","Legacy signatures",1),
    ("I","T-31","Policy choice","Policy is stipulated",2),
    ("I","T-32","Auditor independence","Who audits the auditor",2),
    ("I","T-33","Adjudicator authority","Authority external",2),
    ("I","T-34","Semantic preservation","Migration may change semantics",1),
    ("I","T-35","Revocation completeness","Propagation incomplete",1),
    ("I","T-36","Succession declaration","Who declares N+1",1),
    ("I","T-37","C-V5 open","Generative kernel",1),
    ("I","T-38","C-B4 open","Observability rank",1),
    ("I","T-39","C-E4 open","Decision precedes economics",1),
    ("I","T-40","C-A5 open","Self-reference",1),
    ("I","T-41","Anchor","PUF + specification",0),
    ("I","T-42","Resolver set","Chooser of resolvers",8),
    ("I","T-43","Chooser of resolver set","Self-similar regress",1),
    # ── Part II — Mathematical ───────────────────────────────
    ("II","M-01","Incompleteness","Gödel's first",0),
    ("II","M-02","Unprovability of consistency","Gödel's second",0),
    ("II","M-03","Undefinability of truth","Tarski",0),
    ("II","M-04","Halting","Turing",0),
    ("II","M-05","No set of all sets","Russell",0),
    ("II","M-06","No ordinal of all ordinals","Burali-Forti",0),
    ("II","M-07","No surjection onto power set","Cantor",0),
    ("II","M-08","Self-referential provability","Löb",0),
    ("II","M-09","Curry paradox","Curry",0),
    ("II","M-10","Yablo paradox","Yablo",0),
    ("II","M-11","Berry paradox","Berry",0),
    ("II","M-12","Richard paradox","Richard",0),
    ("II","M-13","Skolem paradox","Skolem",0),
    ("II","M-14","Non-categoricity","Löwenheim-Skolem",0),
    ("II","M-15","Compactness gap","Compactness theorem",0),
    ("II","M-16","Diophantine undecidability","Matiyasevich",0),
    ("II","M-17","Busy beaver","Rado",0),
    ("II","M-18","Kolmogorov incompressibility","Kolmogorov",0),
    ("II","M-19","Chaitin omega","Chaitin",0),
    ("II","M-20","Rice's theorem","Rice",0),
    ("II","M-21","No free lunch (optimization)","Wolpert-Macready",0),
    ("II","M-22","No free lunch (learning)","Wolpert",0),
    ("II","M-23","Computational irreducibility","Wolfram",0),
    ("II","M-24","Undecidability of equivalence","Rice",0),
    ("II","M-25","Non-standard models of arithmetic","Gödel",0),
    ("II","M-26","Independence of CH","Gödel-Cohen",0),
    ("II","M-27","Independence of AC","Cohen",0),
    ("II","M-28","Paris-Harrington","Paris-Harrington",0),
    # ── Part III — Logical ───────────────────────────────────
    ("III","L-01","Liar","Ancient",0),
    ("III","L-02","Sorites","Ancient",0),
    ("III","L-03","Ship of Theseus","Ancient",0),
    ("III","L-04","Münchhausen trilemma","Agrippa",0),
    ("III","L-05","Is-ought gap","Hume",0),
    ("III","L-06","Analytic-synthetic","Quine",0),
    ("III","L-07","Rule-following","Kripke/Wittgenstein",0),
    ("III","L-08","Private language","Wittgenstein",0),
    ("III","L-09","Indeterminacy of translation","Quine",0),
    ("III","L-10","Grue","Goodman",0),
    ("III","L-11","Ravens","Hempel",0),
    ("III","L-12","Underdetermination","Duhem-Quine",0),
    ("III","L-13","Problem of induction","Hume",0),
    ("III","L-14","Frame problem","McCarthy-Hayes",0),
    ("III","L-15","Symbol grounding","Harnad",0),
    # ── Part IV — Computational ──────────────────────────────
    ("IV","C-01","P vs NP","Cook-Levin",0),
    ("IV","C-02","Post correspondence","Post",0),
    ("IV","C-03","Wang tiles","Wang",0),
    ("IV","C-04","Hilbert's tenth","Hilbert",0),
    ("IV","C-05","Turing degree structure","Turing",0),
    ("IV","C-06","Arithmetical hierarchy","Kleene",0),
    ("IV","C-07","Analytical hierarchy","Kleene",0),
    ("IV","C-08","Polynomial hierarchy","Stockmeyer",0),
    ("IV","C-09","Oracle separation","Baker-Gill-Solovay",0),
    ("IV","C-10","Circuit lower bounds","Razborov-Rudich",0),
    ("IV","C-11","Interactive proof limits","Shamir",0),
    ("IV","C-12","PCP theorem","Arora-Safra",0),
    ("IV","C-13","Hardness of approximation","Håstad",0),
    ("IV","C-14","Quantum complexity class","Bernstein-Vazirani",0),
    ("IV","C-15","QMA limits","Kitaev",0),
    ("IV","C-16","Universal quantum simulation","Feynman",0),
    ("IV","C-17","Reversibility of computation","Landauer-Bennett",0),
    ("IV","C-18","Thermodynamics of computation","Bennett",0),
    ("IV","C-19","Decidability of type checking","Various",0),
    ("IV","C-20","Equivalence of grammars","Chomsky",0),
    ("IV","C-21","Inherent parallelism limits","NC vs P",0),
    ("IV","C-22","Amdahl's law","Amdahl",0),
    # ── Part V — Physical ────────────────────────────────────
    ("V","P-01","Uncertainty","Heisenberg",0),
    ("V","P-02","Measurement disturbance","Bohr",0),
    ("V","P-03","No-cloning","Wootters-Zurek",0),
    ("V","P-04","No-deleting","Pati-Braunstein",0),
    ("V","P-05","No-broadcasting","Barnum et al.",0),
    ("V","P-06","No-hiding","Braunstein-Pati",0),
    ("V","P-07","No-communication","Eberhard-Phillips",0),
    ("V","P-08","Bell inequalities","Bell",0),
    ("V","P-09","Nonlocality","Aspect et al.",0),
    ("V","P-10","Measurement problem","Various",0),
    ("V","P-11","Born rule","Born",0),
    ("V","P-12","Arrow of time","Boltzmann",0),
    ("V","P-13","Second law","Clausius",0),
    ("V","P-14","Landauer limit","Landauer",0),
    ("V","P-15","Bekenstein bound","Bekenstein",0),
    ("V","P-16","Holographic principle","'t Hooft-Susskind",0),
    ("V","P-17","Black hole information","Hawking",0),
    ("V","P-18","Cosmological horizon","de Sitter",0),
    ("V","P-19","Poincaré recurrence","Poincaré",0),
    ("V","P-20","Boltzmann brain","Boltzmann",0),
    ("V","P-21","Vacuum energy","Weinberg",0),
    ("V","P-22","Fine-tuning","Various",0),
    ("V","P-23","Lorentz invariance","Lorentz",0),
    ("V","P-24","Speed of light","Einstein",0),
    ("V","P-25","Gravitational horizon","Einstein",0),
    # ── Part VI — Information-Theoretic ──────────────────────
    ("VI","I-01","Entropy","Shannon",0),
    ("VI","I-02","Incompressibility","Kolmogorov",0),
    ("VI","I-03","Channel capacity","Shannon",0),
    ("VI","I-04","Rate-distortion","Shannon",0),
    ("VI","I-05","MDL bound","Rissanen",0),
    ("VI","I-06","Mutual information","Shannon",0),
    ("VI","I-07","Chaitin incompleteness","Chaitin",0),
    ("VI","I-08","Algorithmic sufficiency","Solomonoff",0),
    ("VI","I-09","Universal prior","Solomonoff",0),
    ("VI","I-10","AIXI uncomputability","Hutter",0),
    ("VI","I-11","No-exact-MDL","Rissanen",0),
    ("VI","I-12","Operational entropy","Boltzmann",0),
    # ── Part VII — Cryptographic ─────────────────────────────
    ("VII","K-01","One-way functions","Unproven existence",0),
    ("VII","K-02","P ≠ NP","Assumption",0),
    ("VII","K-03","Factoring hardness","RSA Assumption",0),
    ("VII","K-04","Discrete log","Diffie-Hellman Assumption",0),
    ("VII","K-05","Lattice hardness","PQC Assumption",0),
    ("VII","K-06","Learning with errors","Regev",0),
    ("VII","K-07","Ideal lattice problems","Assumption",0),
    ("VII","K-08","Random oracle model","Bellare-Rogaway",0),
    ("VII","K-09","Universal composability","Canetti",0),
    ("VII","K-10","iO existence","Unproven",0),
    ("VII","K-11","Trusted setup","Ceremony",0),
    ("VII","K-12","Fiat-Shamir heuristic","Non-interactive",0),
    ("VII","K-13","Randomness extraction","Assumption",0),
    ("VII","K-14","Quantum key distribution","BB84",0),
    ("VII","K-15","Post-quantum migration","Migration window",0),
    ("VII","K-16","Quantum adversary model","Assumption",0),
    ("VII","K-17","Side-channel resistance","Physical access",0),
    ("VII","K-18","Composability of primitives","Assumption",0),
    # ── Part VIII — Type-Theoretic ───────────────────────────
    ("VIII","Y-01","Universe hierarchy","Russell/Girard",0),
    ("VIII","Y-02","Girard paradox","Girard",0),
    ("VIII","Y-03","Type-in-type inconsistency","Coquand",0),
    ("VIII","Y-04","Reynolds paradox","Reynolds",0),
    ("VIII","Y-05","Stratification","Quine",0),
    ("VIII","Y-06","Predicativity","Russell",0),
    ("VIII","Y-07","Impredicativity","Coq/Lean",0),
    ("VIII","Y-08","Self-application","Church",0),
    ("VIII","Y-09","Curry-Howard gap","Various",0),
    ("VIII","Y-10","Intensional vs extensional","Martin-Löf",0),
    ("VIII","Y-11","Decidability of conversion","Various",0),
    ("VIII","Y-12","Homotopy levels","Voevodsky",0),
    # ── Part IX — Categorical ────────────────────────────────
    ("IX","K-19","Yoneda embedding","Yoneda",0),
    ("IX","K-20","Adjoint functor existence","SAFT",0),
    ("IX","K-21","Hom-set size","Proper class",0),
    ("IX","K-22","Small vs large","Universe",0),
    ("IX","K-23","Enriched limits","Various",0),
    ("IX","K-24","Banach fixed point","Banach",0),
    ("IX","K-25","Brouwer fixed point","Brouwer",0),
    ("IX","K-26","Knaster-Tarski","Knaster-Tarski",0),
    ("IX","K-27","Diagonal arguments","Lawvere",0),
    ("IX","K-28","Terminal object","Definitional",0),
    # ── Part X — Architectural ───────────────────────────────
    ("X","A-01","Trust anchor","Root of trust",0),
    ("X","A-02","Trusted computing base","Definitional",0),
    ("X","A-03","Bootstrap loader","First instruction",0),
    ("X","A-04","Specification","Stipulated",0),
    ("X","A-05","Resolver","External actor",1),
    ("X","A-06","Human gate","Decision",1),
    ("X","A-07","Physical implementation","Silicon",0),
    ("X","A-08","Supply chain","Foundry",0),
    ("X","A-09","Clock","Physical",0),
    ("X","A-10","Power","Physical",0),
    ("X","A-11","Cooling","Physical",0),
    ("X","A-12","Time-to-market","Economic",0),
    ("X","A-13","Interface contract","Stipulated",0),
    ("X","A-14","Failure mode","Undecidable",0),
    ("X","A-15","Boundary","Drawing",0),
    # ── Part XI — Epistemic ──────────────────────────────────
    ("XI","E-01","Observability rank","Kalman",0),
    ("XI","E-02","Blind spot register","Kalman",0),
    ("XI","E-03","Self-observation","Gödel/Tarski",0),
    ("XI","E-04","Cartesian doubt","Descartes",0),
    ("XI","E-05","Cogito","Descartes",0),
    ("XI","E-06","Münchhausen trilemma","Agrippa",0),
    ("XI","E-07","Regress argument","Sextus",0),
    ("XI","E-08","Fundamental disagreement","Various",0),
    ("XI","E-09","Underdetermination","Duhem-Quine",0),
    ("XI","E-10","Theory-laden observation","Hanson",0),
    ("XI","E-11","Incommensurability","Kuhn",0),
    ("XI","E-12","Falsifiability limit","Popper",0),
    ("XI","E-13","Research programme","Lakatos",0),
    ("XI","E-14","Paradigm shift","Kuhn",0),
    ("XI","E-15","Sociology of knowledge","Various",0),
    ("XI","E-16","Bounded rationality","Simon",0),
    ("XI","E-17","Heuristics","Kahneman-Tversky",0),
    ("XI","E-18","Predictive coding error","Friston",0),
    # ── Part XII — Statistical ───────────────────────────────
    ("XII","S-01","Bias-variance","Geman et al.",0),
    ("XII","S-02","Overfitting","Various",0),
    ("XII","S-03","Distribution shift","Various",0),
    ("XII","S-04","Covariate shift","Shimodaira",0),
    ("XII","S-05","Concept drift","Various",0),
    ("XII","S-06","Unidentifiability","Various",0),
    ("XII","S-07","Simpson paradox","Simpson",0),
    ("XII","S-08","Berkson paradox","Berkson",0),
    ("XII","S-09","Ecological fallacy","Robinson",0),
    ("XII","S-10","Regression to mean","Galton",0),
    ("XII","S-11","Multiple comparisons","Various",0),
    ("XII","S-12","Base rate fallacy","Kahneman-Tversky",0),
    ("XII","S-13","Conjunction fallacy","Tversky-Kahneman",0),
    ("XII","S-14","Look-elsewhere effect","Various",0),
    ("XII","S-15","Garden of forking paths","Gelman-Loken",0),
    # ── Part XIII — Governance ───────────────────────────────
    ("XIII","G-01","Chooser","Selection",1),
    ("XIII","G-02","Grantor","Grant",1),
    ("XIII","G-03","Accepter","Acceptance",1),
    ("XIII","G-04","Signer","Signature",1),
    ("XIII","G-05","Auditor","Independence",1),
    ("XIII","G-06","Adjudicator","Authority",1),
    ("XIII","G-07","Declarer","Succession",1),
    ("XIII","G-08","Human accountability","Responsibility",1),
    ("XIII","G-09","Legitimacy","Source",1),
    ("XIII","G-10","Sovereignty","Ultimate authority",1),
    ("XIII","G-11","Mandate","Consent",1),
    ("XIII","G-12","Consent of governed","Rousseau","N"),
    ("XIII","G-13","Rule of law","Various",1),
    ("XIII","G-14","Emergency powers","Exception",1),
    ("XIII","G-15","Exit right","Hirschman",1),
    # ── Part XIV — Economic ──────────────────────────────────
    ("XIV","N-01","Decision","When delta > 0",1),
    ("XIV","N-02","Opportunity cost","Foregone",0),
    ("XIV","N-03","Subjective value","Menger",0),
    ("XIV","N-04","Time preference","Böhm-Bawerk",0),
    ("XIV","N-05","Risk tolerance","Various",0),
    ("XIV","N-06","Arrow impossibility","Arrow",0),
    ("XIV","N-07","Sen paradox","Sen",0),
    ("XIV","N-08","Condorcet paradox","Condorcet",0),
    ("XIV","N-09","Gibbard-Satterthwaite","Various",0),
    ("XIV","N-10","Mechanism design limits","Hurwicz",0),
    ("XIV","N-11","Revelation principle","Myerson",0),
    ("XIV","N-12","Myerson-Satterthwaite","Various",0),
    ("XIV","N-13","Coase assumptions","Coase",0),
    ("XIV","N-14","Free rider","Olson",0),
    ("XIV","N-15","Tragedy of commons","Hardin",0),
    ("XIV","N-16","Principal-agent","Jensen-Meckling",0),
    ("XIV","N-17","Moral hazard","Various",0),
    ("XIV","N-18","Adverse selection","Akerlof",0),
    # ── Part XV — Distributed ────────────────────────────────
    ("XV","D-01","FLP impossibility","Fischer-Lynch-Paterson",0),
    ("XV","D-02","Byzantine generals","Lamport et al.",0),
    ("XV","D-03","CAP theorem","Brewer",0),
    ("XV","D-04","PACELC","Abadi",0),
    ("XV","D-05","Two generals","Akkoyunlu et al.",0),
    ("XV","D-06","Clock synchronization","Lamport",0),
    ("XV","D-07","Partition tolerance","Brewer",0),
    ("XV","D-08","Consensus impossibility","FLP",0),
    ("XV","D-09","Snapshot consistency","Chandy-Lamport",0),
    ("XV","D-10","Vector clock gaps","Lamport",0),
    ("XV","D-11","Ordering","Lamport",0),
    ("XV","D-12","Atomicity","Various",0),
    ("XV","D-13","Linearizability","Herlihy-Wing",0),
    ("XV","D-14","Serializability","Various",0),
    ("XV","D-15","Progress guarantee","Various",0),
    # ── Part XVI — Physical Implementation ───────────────────
    ("XVI","H-01","Silicon variance","Foundry",0),
    ("XVI","H-02","Side channels (power)","Kocher",0),
    ("XVI","H-03","Side channels (timing)","Kocher",0),
    ("XVI","H-04","Side channels (EM)","Various",0),
    ("XVI","H-05","Fault injection","Boneh-DeMillo-Lipton",0),
    ("XVI","H-06","Rowhammer","Kim et al.",0),
    ("XVI","H-07","Spectre","Kocher et al.",0),
    ("XVI","H-08","Meltdown","Lipp et al.",0),
    ("XVI","H-09","Hardware Trojans","Various",0),
    ("XVI","H-10","Supply chain compromise","Various",0),
    ("XVI","H-11","Foundry trust","Geopolitics",0),
    ("XVI","H-12","Packaging tamper","Various",0),
    ("XVI","H-13","Aging/degradation","Various",0),
    ("XVI","H-14","Thermal limits","Physics",0),
    ("XVI","H-15","Power limits","Physics",0),
    # ── Part XVII — Cognitive ────────────────────────────────
    ("XVII","B-01","Bounded rationality","Simon",0),
    ("XVII","B-02","Heuristics and biases","Kahneman-Tversky",0),
    ("XVII","B-03","Dual process","Various",0),
    ("XVII","B-04","Attention limits","Miller",0),
    ("XVII","B-05","Working memory","Miller",0),
    ("XVII","B-06","Chunking","Miller",0),
    ("XVII","B-07","Free energy","Friston",0),
    ("XVII","B-08","Predictive coding","Rao-Ballard",0),
    ("XVII","B-09","Global workspace","Baars",0),
    ("XVII","B-10","Hard problem","Chalmers",0),
    ("XVII","B-11","Explanatory gap","Levine",0),
    ("XVII","B-12","Mary's room","Jackson",0),
    ("XVII","B-13","Philosophical zombie","Chalmers",0),
    ("XVII","B-14","Chinese room","Searle",0),
    ("XVII","B-15","Binding problem","Various",0),
    ("XVII","B-16","Qualia","Various",0),
    ("XVII","B-17","Intentionality","Brentano",0),
    ("XVII","B-18","Aboutness","Various",0),
    ("XVII","B-19","Self-model","Metzinger",0),
    ("XVII","B-20","Autobiographical memory","Various",0),
    ("XVII","B-21","Reconstruction of memory","Bartlett",0),
    ("XVII","B-22","Confabulation","Various",0),
    ("XVII","B-23","Cognitive dissonance","Festinger",0),
    ("XVII","B-24","Motivated reasoning","Kunda",0),
    ("XVII","B-25","Dunning-Kruger","Dunning-Kruger",0),
    # ── Part XVIII — Semantic ────────────────────────────────
    ("XVIII","Z-01","Meaning","Various",0),
    ("XVIII","Z-02","Reference","Frege",0),
    ("XVIII","Z-03","Sense","Frege",0),
    ("XVIII","Z-04","Translation indeterminacy","Quine",0),
    ("XVIII","Z-05","Interpretation","Davidson",0),
    ("XVIII","Z-06","Speech acts","Austin-Searle",0),
    ("XVIII","Z-07","Implicature","Grice",0),
    ("XVIII","Z-08","Presupposition","Various",0),
    ("XVIII","Z-09","Context-dependence","Various",0),
    ("XVIII","Z-10","Vagueness","Sorites",0),
    ("XVIII","Z-11","Metaphor","Lakoff-Johnson",0),
    ("XVIII","Z-12","Symbol grounding","Harnad",0),
    # ── Part XIX — Ethical ───────────────────────────────────
    ("XIX","U-01","Is-ought gap","Hume",0),
    ("XIX","U-02","Fact-value distinction","Hume",0),
    ("XIX","U-03","Moral realism","Various",0),
    ("XIX","U-04","Moral anti-realism","Various",0),
    ("XIX","U-05","Moral disagreement","Various",0),
    ("XIX","U-06","Moral luck","Williams-Nagel",0),
    ("XIX","U-07","Value pluralism","Berlin",0),
    ("XIX","U-08","Incommensurability","Various",0),
    ("XIX","U-09","Rights conflicts","Various",0),
    ("XIX","U-10","Trolley problems","Foot",0),
    ("XIX","U-11","Doctrine of double effect","Aquinas",0),
    ("XIX","U-12","Moral uncertainty","Various",0),
    # ── Part XX — Legal ──────────────────────────────────────
    ("XX","W-01","Rule of law","Various",0),
    ("XX","W-02","Sovereignty","Bodin",0),
    ("XX","W-03","Jurisdiction","Various",0),
    ("XX","W-04","Standing","Various",0),
    ("XX","W-05","Legitimacy","Various",0),
    ("XX","W-06","Emergency powers","Various",0),
    ("XX","W-07","Hard cases","Dworkin",0),
    ("XX","W-08","Indeterminacy of law","Various",0),
    ("XX","W-09","Gap in law","Various",0),
    ("XX","W-10","Constitutional moment","Ackerman",0),
    ("XX","W-11","Constitutional amendment","Various",0),
    ("XX","W-12","Judicial review","Marbury",0),
    # ── Part XXI — Biological ────────────────────────────────
    ("XXI","Q-01","Imperfect adaptation","Various",0),
    ("XXI","Q-02","Red Queen","Van Valen",0),
    ("XXI","Q-03","Selection shadow","Medawar",0),
    ("XXI","Q-04","Pleiotropy","Various",0),
    ("XXI","Q-05","Epistasis","Various",0),
    ("XXI","Q-06","Fitness landscape ruggedness","Wright",0),
    ("XXI","Q-07","Genetic drift","Wright",0),
    ("XXI","Q-08","Muller's ratchet","Muller",0),
    ("XXI","Q-09","Error catastrophe","Eigen",0),
    ("XXI","Q-10","Eigen paradox","Eigen",0),
    ("XXI","Q-11","Origin of life","Various",0),
    ("XXI","Q-12","Origin of genetic code","Various",0),
    # ── Part XXII — Systems ──────────────────────────────────
    ("XXII","X-01","Fault tolerance limits","Various",0),
    ("XXII","X-02","Byzantine bound","Lamport",0),
    ("XXII","X-03","Single point of failure","Various",0),
    ("XXII","X-04","Cascading failure","Various",0),
    ("XXII","X-05","Race conditions","Various",0),
    ("XXII","X-06","Deadlock","Coffman",0),
    ("XXII","X-07","Livelock","Various",0),
    ("XXII","X-08","Resource exhaustion","Various",0),
    ("XXII","X-09","Denial of service","Various",0),
    ("XXII","X-10","Emergent behavior","Various",0),
    ("XXII","X-11","Chaos","Lorenz",0),
    ("XXII","X-12","Unpredictability","Various",0),
    # ── Part XXIII — Foundational ────────────────────────────
    ("XXIII","F-01","Being","Parmenides",0),
    ("XXIII","F-02","Becoming","Heraclitus",0),
    ("XXIII","F-03","Identity","Various",0),
    ("XXIII","F-04","Change","Aristotle",0),
    ("XXIII","F-05","Causation","Hume",0),
    ("XXIII","F-06","Modality","Kripke",0),
    ("XXIII","F-07","Time","McTaggart",0),
    ("XXIII","F-08","Space","Various",0),
    ("XXIII","F-09","Substance","Aristotle",0),
    ("XXIII","F-10","Universal","Various",0),
    ("XXIII","F-11","Particular","Various",0),
    ("XXIII","F-12","Existence","Various",0),
    # ── Part XXIV — Terminal ─────────────────────────────────
    ("XXIV","Ω","The act of proceeding","This thread",0),
]


@dataclass(frozen=True)
class Residual:
    class_id: str
    class_name: str
    id: str
    name: str
    source: str
    arity: object


def _build() -> dict[str, Residual]:
    out: dict[str, Residual] = {}
    for cid, rid, name, source, arity in ENTRIES:
        out[rid] = Residual(cid, CLASSES[cid], rid, name, source, arity)
    return out


REGISTER: dict[str, Residual] = _build()
TOTAL: int = len(REGISTER)


def get(rid: str) -> Residual:
    if rid not in REGISTER:
        raise KeyError(f"unknown residual: {rid}")
    return REGISTER[rid]


def by_class(class_id: str) -> list[Residual]:
    return [r for r in REGISTER.values() if r.class_id == class_id]


def search(substr: str) -> list[Residual]:
    s = substr.lower()
    return [r for r in REGISTER.values()
            if s in r.name.lower() or s in r.source.lower()]


def is_valid(rid: str) -> bool:
    return rid in REGISTER


def report() -> dict:
    from collections import Counter
    by_class_count = Counter(r.class_name for r in REGISTER.values())
    arity = Counter(r.arity for r in REGISTER.values())
    return {
        "total": TOTAL,
        "classes": len(CLASSES),
        "by_class": dict(by_class_count),
        "arity_distribution": {str(k): v for k, v in arity.items()},
    }
